apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: greeting-controller-sa
      containers:
      - name: flask
        image: irodotos/hy548:ass4-2
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
        env:
        - name: MESSAGE
          value: "Hello, hy548 !"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-controller-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-role-binding
subjects:
- kind: ServiceAccount
  name: greeting-controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io