apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-content
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-content
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hy548-configmap
data:
  build-script.sh: |
    #!/bin/bash
    apt-get update
    apt-get install -y git wget make
    wget https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_linux-amd64.deb
    dpkg --install hugo_extended_0.111.3_linux-amd64.deb
    git clone https://github.com/chazapis/hy548.git
    cd hy548
    git submodule update --init --recursive
    make all
    cp -r /html/public/* /website

---

apiVersion: batch/v1
kind: Job
metadata:
  name: hy548-job
spec:
  template:
    spec:
      containers:
      - name: build
        image: ubuntu:20.04
        command: ["/bin/bash", "/scripts/build-script.sh"]
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
        - name: website-content
          mountPath: /website
      restartPolicy: Never
      volumes:
      - name: scripts-volume
        configMap:
          name: hy548-configmap
      - name: website-content
        persistentVolumeClaim:
          claimName: website-content
  backoffLimit: 4

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: website-update
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update
            image: ubuntu:20.04
            command: ["/bin/bash", "/scripts/build-script.sh"]
            volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
            - name: website-content
              mountPath: /website
          restartPolicy: OnFailure
          volumes:
          - name: scripts-volume
            configMap:
              name: hy548-configmap
          - name: website-content
            persistentVolumeClaim:
              claimName: website-content

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.23.3-alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: website-content
      mountPath: /usr/share/nginx/html
  volumes:
  - name: website-content
    persistentVolumeClaim:
      claimName: website-content