apiVersion: v1
kind: ConfigMap
metadata:
  name: hy548-configmap
data:
  build-script.sh: |
    #!/bin/bash
    apt-get update
    apt-get install -y git wget
    apt-get install make -y
    wget https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_linux-amd64.deb
    dpkg --install hugo_extended_0.111.3_linux-amd64.deb
    git clone https://github.com/chazapis/hy548.git
    cd hy548
    git submodule update --init --recursive
    make all

---

apiVersion: batch/v1
kind: Job
metadata:
  name: hy548-job
spec:
  template:
    spec:
      containers:
      - name: build
        image: ubuntu:20.04
        command: ["/bin/bash", "/scripts/build-script.sh"]
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: scripts-volume
        configMap:
          name: hy548-configmap